<?php

/**
 * depende do FlashMessengerHelper
 * @reference https://github.com/zendframework/zf2/issues/4477#issuecomment-38681934
 */

$flash = $this->flashMessenger();

//Utilizar o alert do Bootstrap 3
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

//imprime mensagens antes do redirect
echo $flash->renderCurrent('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->renderCurrent('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));

//apagam mensagens utilizadas sem precisar do redirect
$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();

//imprime mensagens depois do redirect
echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));